/*
* Generated by SGWrapperGen - DO NOT EDIT!
*
* SwinGame wrapper for C - Audio
*
* Wrapping sgAudio.pas
*/

#ifndef sgAudio
#define sgAudio

#include <stdint.h>

#ifndef __cplusplus
  #include <stdbool.h>
#endif

#include "Types.h"

bool audio_ready();
void close_audio();
void fade_music_named_in(const char *name, int32_t ms);
void fade_music_in(music mus, int32_t ms);
void fade_music_in_with_loops(music mus, int32_t loops, int32_t ms);
void fade_music_named_in_with_loops(const char *name, int32_t loops, int32_t ms);
void fade_music_out(int32_t ms);
void free_music(music *mus);
void free_sound_effect(sound_effect *effect);
bool has_music(const char *name);
bool has_sound_effect(const char *name);
music load_music(const char *filename);
music load_music_named(const char *name, const char *filename);
sound_effect load_sound_effect(const char *filename);
sound_effect load_sound_effect_named(const char *name, const char *filename);
void music_filename(music mus, char *result);
void music_name(music mus, char *result);
music music_named(const char *name);
bool music_playing();
float music_volume();
void open_audio();
void pause_music();
void play_music_named(const char *name);
void play_music(music mus);
void play_music_with_loops(music mus, int32_t loops);
void play_music_named_with_loops(const char *name, int32_t loops);
void play_sound_effect(sound_effect effect);
void play_sound_effect_named(const char *name);
void play_sound_effect_with_volume(sound_effect effect, float vol);
void play_sound_effect_with_loop(sound_effect effect, int32_t loops);
void play_sound_effect_named_with_volume(const char *name, float vol);
void play_sound_effect_named_with_loop(const char *name, int32_t loops);
void play_sound_effect_with_loop_and_volume(sound_effect effect, int32_t loops, float vol);
void play_sound_effect_named_with_loop_and_volume(const char *name, int32_t loops, float vol);
void release_all_music();
void release_all_sound_effects();
void release_music(const char *name);
void release_sound_effect(const char *name);
void resume_music();
void set_music_volume(float value);
void sound_effect_filename(sound_effect effect, char *result);
void sound_effect_name(sound_effect effect, char *result);
sound_effect sound_effect_named(const char *name);
bool sound_effect_named_playing(const char *name);
bool sound_effect_playing(sound_effect effect);
void stop_music();
void stop_sound_effect(sound_effect effect);
void stop_sound_effect_named(const char *name);
bool try_open_audio();

#ifdef __cplusplus
// C++ overloaded functions
void fade_music_in(const char *name, int32_t ms);
void fade_music_in(music mus, int32_t loops, int32_t ms);
void fade_music_in(const char *name, int32_t loops, int32_t ms);
void free_music(music &mus);
void free_sound_effect(sound_effect &effect);
void play_music(const char *name);
void play_music(music mus, int32_t loops);
void play_music(const char *name, int32_t loops);
void play_sound_effect(const char *name);
void play_sound_effect(sound_effect effect, float vol);
void play_sound_effect(sound_effect effect, int32_t loops);
void play_sound_effect(const char *name, float vol);
void play_sound_effect(const char *name, int32_t loops);
void play_sound_effect(sound_effect effect, int32_t loops, float vol);
void play_sound_effect(const char *name, int32_t loops, float vol);
bool sound_effect_playing(const char *name);
void stop_sound_effect(const char *name);

#endif

#endif

