/*
* Generated by SGWrapperGen - DO NOT EDIT!
*
* SwinGame wrapper for C - Graphics
*
* Wrapping sgGraphics.pas
*/

#include "SGSDK.h"
#include "Graphics.h"

#include "Types.h"

resolution available_resolution(int32_t idx)
{
    return sg_Graphics_AvailableResolution(idx);
}

unsigned char blue_of(color c)
{
    return sg_Graphics_BlueOf(c);
}

float brightness_of(color c)
{
    return sg_Graphics_BrightnessOf(c);
}

void clear_screen()
{
    sg_Graphics_ClearScreen();
}

#ifdef __cplusplus

void clear_screen(color toColor)
{
    sg_Graphics_ClearScreenTo(toColor);
}

#endif

void clear_screen_to(color toColor)
{
    sg_Graphics_ClearScreenTo(toColor);
}

color color_alice_blue()
{
    return sg_Graphics_ColorAliceBlue();
}

color color_antique_white()
{
    return sg_Graphics_ColorAntiqueWhite();
}

color color_aqua()
{
    return sg_Graphics_ColorAqua();
}

color color_aquamarine()
{
    return sg_Graphics_ColorAquamarine();
}

color color_azure()
{
    return sg_Graphics_ColorAzure();
}

color color_beige()
{
    return sg_Graphics_ColorBeige();
}

color color_bisque()
{
    return sg_Graphics_ColorBisque();
}

color color_black()
{
    return sg_Graphics_ColorBlack();
}

color color_blanched_almond()
{
    return sg_Graphics_ColorBlanchedAlmond();
}

color color_blue()
{
    return sg_Graphics_ColorBlue();
}

color color_blue_violet()
{
    return sg_Graphics_ColorBlueViolet();
}

color color_bright_green()
{
    return sg_Graphics_ColorBrightGreen();
}

color color_brown()
{
    return sg_Graphics_ColorBrown();
}

color color_burly_wood()
{
    return sg_Graphics_ColorBurlyWood();
}

color color_cadet_blue()
{
    return sg_Graphics_ColorCadetBlue();
}

color color_chartreuse()
{
    return sg_Graphics_ColorChartreuse();
}

color color_chocolate()
{
    return sg_Graphics_ColorChocolate();
}

#ifdef __cplusplus

void color_components(color c, unsigned char &r, unsigned char &g, unsigned char &b, unsigned char &a)
{
    sg_Graphics_ColorComponents(c, &r, &g, &b, &a);
}

#endif

void color_components(color c, unsigned char *r, unsigned char *g, unsigned char *b, unsigned char *a)
{
    sg_Graphics_ColorComponents(c, r, g, b, a);
}

color color_coral()
{
    return sg_Graphics_ColorCoral();
}

color color_cornflower_blue()
{
    return sg_Graphics_ColorCornflowerBlue();
}

color color_cornsilk()
{
    return sg_Graphics_ColorCornsilk();
}

color color_crimson()
{
    return sg_Graphics_ColorCrimson();
}

color color_cyan()
{
    return sg_Graphics_ColorCyan();
}

color color_dark_blue()
{
    return sg_Graphics_ColorDarkBlue();
}

color color_dark_cyan()
{
    return sg_Graphics_ColorDarkCyan();
}

color color_dark_goldenrod()
{
    return sg_Graphics_ColorDarkGoldenrod();
}

color color_dark_gray()
{
    return sg_Graphics_ColorDarkGray();
}

color color_dark_green()
{
    return sg_Graphics_ColorDarkGreen();
}

color color_dark_khaki()
{
    return sg_Graphics_ColorDarkKhaki();
}

color color_dark_magenta()
{
    return sg_Graphics_ColorDarkMagenta();
}

color color_dark_olive_green()
{
    return sg_Graphics_ColorDarkOliveGreen();
}

color color_dark_orange()
{
    return sg_Graphics_ColorDarkOrange();
}

color color_dark_orchid()
{
    return sg_Graphics_ColorDarkOrchid();
}

color color_dark_red()
{
    return sg_Graphics_ColorDarkRed();
}

color color_dark_salmon()
{
    return sg_Graphics_ColorDarkSalmon();
}

color color_dark_sea_green()
{
    return sg_Graphics_ColorDarkSeaGreen();
}

color color_dark_slate_blue()
{
    return sg_Graphics_ColorDarkSlateBlue();
}

color color_dark_slate_gray()
{
    return sg_Graphics_ColorDarkSlateGray();
}

color color_dark_turquoise()
{
    return sg_Graphics_ColorDarkTurquoise();
}

color color_dark_violet()
{
    return sg_Graphics_ColorDarkViolet();
}

color color_deep_pink()
{
    return sg_Graphics_ColorDeepPink();
}

color color_deep_sky_blue()
{
    return sg_Graphics_ColorDeepSkyBlue();
}

color color_dim_gray()
{
    return sg_Graphics_ColorDimGray();
}

color color_dodger_blue()
{
    return sg_Graphics_ColorDodgerBlue();
}

color color_firebrick()
{
    return sg_Graphics_ColorFirebrick();
}

color color_floral_white()
{
    return sg_Graphics_ColorFloralWhite();
}

color color_forest_green()
{
    return sg_Graphics_ColorForestGreen();
}

color color_fuchsia()
{
    return sg_Graphics_ColorFuchsia();
}

color color_gainsboro()
{
    return sg_Graphics_ColorGainsboro();
}

color color_ghost_white()
{
    return sg_Graphics_ColorGhostWhite();
}

color color_gold()
{
    return sg_Graphics_ColorGold();
}

color color_goldenrod()
{
    return sg_Graphics_ColorGoldenrod();
}

color color_gray()
{
    return sg_Graphics_ColorGray();
}

color color_green()
{
    return sg_Graphics_ColorGreen();
}

color color_green_yellow()
{
    return sg_Graphics_ColorGreenYellow();
}

color color_grey()
{
    return sg_Graphics_ColorGrey();
}

color color_honeydew()
{
    return sg_Graphics_ColorHoneydew();
}

color color_hot_pink()
{
    return sg_Graphics_ColorHotPink();
}

color color_indian_red()
{
    return sg_Graphics_ColorIndianRed();
}

color color_indigo()
{
    return sg_Graphics_ColorIndigo();
}

color color_ivory()
{
    return sg_Graphics_ColorIvory();
}

color color_khaki()
{
    return sg_Graphics_ColorKhaki();
}

color color_lavender()
{
    return sg_Graphics_ColorLavender();
}

color color_lavender_blush()
{
    return sg_Graphics_ColorLavenderBlush();
}

color color_lawn_green()
{
    return sg_Graphics_ColorLawnGreen();
}

color color_lemon_chiffon()
{
    return sg_Graphics_ColorLemonChiffon();
}

color color_light_blue()
{
    return sg_Graphics_ColorLightBlue();
}

color color_light_coral()
{
    return sg_Graphics_ColorLightCoral();
}

color color_light_cyan()
{
    return sg_Graphics_ColorLightCyan();
}

color color_light_goldenrod_yellow()
{
    return sg_Graphics_ColorLightGoldenrodYellow();
}

color color_light_gray()
{
    return sg_Graphics_ColorLightGray();
}

color color_light_green()
{
    return sg_Graphics_ColorLightGreen();
}

color color_light_grey()
{
    return sg_Graphics_ColorLightGrey();
}

color color_light_pink()
{
    return sg_Graphics_ColorLightPink();
}

color color_light_salmon()
{
    return sg_Graphics_ColorLightSalmon();
}

color color_light_sea_green()
{
    return sg_Graphics_ColorLightSeaGreen();
}

color color_light_sky_blue()
{
    return sg_Graphics_ColorLightSkyBlue();
}

color color_light_slate_gray()
{
    return sg_Graphics_ColorLightSlateGray();
}

color color_light_steel_blue()
{
    return sg_Graphics_ColorLightSteelBlue();
}

color color_light_yellow()
{
    return sg_Graphics_ColorLightYellow();
}

color color_lime()
{
    return sg_Graphics_ColorLime();
}

color color_lime_green()
{
    return sg_Graphics_ColorLimeGreen();
}

color color_linen()
{
    return sg_Graphics_ColorLinen();
}

color color_magenta()
{
    return sg_Graphics_ColorMagenta();
}

color color_maroon()
{
    return sg_Graphics_ColorMaroon();
}

color color_medium_aquamarine()
{
    return sg_Graphics_ColorMediumAquamarine();
}

color color_medium_blue()
{
    return sg_Graphics_ColorMediumBlue();
}

color color_medium_orchid()
{
    return sg_Graphics_ColorMediumOrchid();
}

color color_medium_purple()
{
    return sg_Graphics_ColorMediumPurple();
}

color color_medium_sea_green()
{
    return sg_Graphics_ColorMediumSeaGreen();
}

color color_medium_slate_blue()
{
    return sg_Graphics_ColorMediumSlateBlue();
}

color color_medium_spring_green()
{
    return sg_Graphics_ColorMediumSpringGreen();
}

color color_medium_turquoise()
{
    return sg_Graphics_ColorMediumTurquoise();
}

color color_medium_violet_red()
{
    return sg_Graphics_ColorMediumVioletRed();
}

color color_midnight_blue()
{
    return sg_Graphics_ColorMidnightBlue();
}

color color_mint_cream()
{
    return sg_Graphics_ColorMintCream();
}

color color_misty_rose()
{
    return sg_Graphics_ColorMistyRose();
}

color color_moccasin()
{
    return sg_Graphics_ColorMoccasin();
}

color color_navajo_white()
{
    return sg_Graphics_ColorNavajoWhite();
}

color color_navy()
{
    return sg_Graphics_ColorNavy();
}

color color_old_lace()
{
    return sg_Graphics_ColorOldLace();
}

color color_olive()
{
    return sg_Graphics_ColorOlive();
}

color color_olive_drab()
{
    return sg_Graphics_ColorOliveDrab();
}

color color_orange()
{
    return sg_Graphics_ColorOrange();
}

color color_orange_red()
{
    return sg_Graphics_ColorOrangeRed();
}

color color_orchid()
{
    return sg_Graphics_ColorOrchid();
}

color color_pale_goldenrod()
{
    return sg_Graphics_ColorPaleGoldenrod();
}

color color_pale_green()
{
    return sg_Graphics_ColorPaleGreen();
}

color color_pale_turquoise()
{
    return sg_Graphics_ColorPaleTurquoise();
}

color color_pale_violet_red()
{
    return sg_Graphics_ColorPaleVioletRed();
}

color color_papaya_whip()
{
    return sg_Graphics_ColorPapayaWhip();
}

color color_peach_puff()
{
    return sg_Graphics_ColorPeachPuff();
}

color color_peru()
{
    return sg_Graphics_ColorPeru();
}

color color_pink()
{
    return sg_Graphics_ColorPink();
}

color color_plum()
{
    return sg_Graphics_ColorPlum();
}

color color_powder_blue()
{
    return sg_Graphics_ColorPowderBlue();
}

color color_purple()
{
    return sg_Graphics_ColorPurple();
}

color color_red()
{
    return sg_Graphics_ColorRed();
}

color color_rosy_brown()
{
    return sg_Graphics_ColorRosyBrown();
}

color color_royal_blue()
{
    return sg_Graphics_ColorRoyalBlue();
}

color color_saddle_brown()
{
    return sg_Graphics_ColorSaddleBrown();
}

color color_salmon()
{
    return sg_Graphics_ColorSalmon();
}

color color_sandy_brown()
{
    return sg_Graphics_ColorSandyBrown();
}

color color_sea_green()
{
    return sg_Graphics_ColorSeaGreen();
}

color color_sea_shell()
{
    return sg_Graphics_ColorSeaShell();
}

color color_sienna()
{
    return sg_Graphics_ColorSienna();
}

color color_silver()
{
    return sg_Graphics_ColorSilver();
}

color color_sky_blue()
{
    return sg_Graphics_ColorSkyBlue();
}

color color_slate_blue()
{
    return sg_Graphics_ColorSlateBlue();
}

color color_slate_gray()
{
    return sg_Graphics_ColorSlateGray();
}

color color_snow()
{
    return sg_Graphics_ColorSnow();
}

color color_spring_green()
{
    return sg_Graphics_ColorSpringGreen();
}

color color_steel_blue()
{
    return sg_Graphics_ColorSteelBlue();
}

color color_swinburne_red()
{
    return sg_Graphics_ColorSwinburneRed();
}

color color_tan()
{
    return sg_Graphics_ColorTan();
}

color color_teal()
{
    return sg_Graphics_ColorTeal();
}

color color_thistle()
{
    return sg_Graphics_ColorThistle();
}

void color_to_string(color c, char *result)
{
    sg_Graphics_ColorToString(c, result);
}

color color_tomato()
{
    return sg_Graphics_ColorTomato();
}

color color_transparent()
{
    return sg_Graphics_ColorTransparent();
}

color color_turquoise()
{
    return sg_Graphics_ColorTurquoise();
}

color color_violet()
{
    return sg_Graphics_ColorViolet();
}

color color_wheat()
{
    return sg_Graphics_ColorWheat();
}

color color_white()
{
    return sg_Graphics_ColorWhite();
}

color color_white_smoke()
{
    return sg_Graphics_ColorWhiteSmoke();
}

color color_yellow()
{
    return sg_Graphics_ColorYellow();
}

color color_yellow_green()
{
    return sg_Graphics_ColorYellowGreen();
}

#ifdef __cplusplus

rectangle current_clip()
{
    return sg_Graphics_CurrentWindowClip();
}

#endif

rectangle current_window_clip()
{
    return sg_Graphics_CurrentWindowClip();
}

#ifdef __cplusplus

rectangle current_clip(window wnd)
{
    return sg_Graphics_CurrentClipForWindow(wnd);
}

#endif

rectangle current_clip_for_window(window wnd)
{
    return sg_Graphics_CurrentClipForWindow(wnd);
}

#ifdef __cplusplus

rectangle current_clip(bitmap bmp)
{
    return sg_Graphics_CurrentClipForBitmap(bmp);
}

#endif

rectangle current_clip_for_bitmap(bitmap bmp)
{
    return sg_Graphics_CurrentClipForBitmap(bmp);
}

void draw_circle(color clr, float x, float y, float radius)
{
    sg_Graphics_DrawCircle(clr, x, y, radius);
}

#ifdef __cplusplus

void draw_circle(color clr, const circle &c)
{
    sg_Graphics_DrawCircleStruct(clr, &c);
}

#endif

void draw_circle_struct(color clr, const circle *c)
{
    sg_Graphics_DrawCircleStruct(clr, c);
}

void draw_circle_struct_byval(color clr, const circle c)
{
    sg_Graphics_DrawCircleStruct(clr, &c);
}

#ifdef __cplusplus

void draw_circle(color clr, const circle &c, const drawing_options &opts)
{
    sg_Graphics_DrawCircleStructOpts(clr, &c, &opts);
}

#endif

void draw_circle_struct_opts(color clr, const circle *c, const drawing_options *opts)
{
    sg_Graphics_DrawCircleStructOpts(clr, c, opts);
}

void draw_circle_struct_opts_byval(color clr, const circle c, const drawing_options opts)
{
    sg_Graphics_DrawCircleStructOpts(clr, &c, &opts);
}

#ifdef __cplusplus

void draw_circle(color clr, float x, float y, float radius, const drawing_options &opts)
{
    sg_Graphics_DrawCircleOpts(clr, x, y, radius, &opts);
}

#endif

void draw_circle_opts(color clr, float x, float y, float radius, const drawing_options *opts)
{
    sg_Graphics_DrawCircleOpts(clr, x, y, radius, opts);
}

void draw_circle_opts_byval(color clr, float x, float y, float radius, const drawing_options opts)
{
    sg_Graphics_DrawCircleOpts(clr, x, y, radius, &opts);
}

void draw_ellipse(color clr, float xPos, float yPos, float width, float height)
{
    sg_Graphics_DrawEllipse(clr, xPos, yPos, width, height);
}

#ifdef __cplusplus

void draw_ellipse(color clr, const rectangle &rec)
{
    sg_Graphics_DrawEllipseStruct(clr, &rec);
}

#endif

void draw_ellipse_struct(color clr, const rectangle *rec)
{
    sg_Graphics_DrawEllipseStruct(clr, rec);
}

void draw_ellipse_struct_byval(color clr, const rectangle rec)
{
    sg_Graphics_DrawEllipseStruct(clr, &rec);
}

#ifdef __cplusplus

void draw_ellipse(color clr, const rectangle &rec, const drawing_options &opts)
{
    sg_Graphics_DrawEllipseStructOpts(clr, &rec, &opts);
}

#endif

void draw_ellipse_struct_opts(color clr, const rectangle *rec, const drawing_options *opts)
{
    sg_Graphics_DrawEllipseStructOpts(clr, rec, opts);
}

void draw_ellipse_struct_opts_byval(color clr, const rectangle rec, const drawing_options opts)
{
    sg_Graphics_DrawEllipseStructOpts(clr, &rec, &opts);
}

#ifdef __cplusplus

void draw_ellipse(color clr, float xPos, float yPos, float width, float height, const drawing_options &opts)
{
    sg_Graphics_DrawEllipseOpts(clr, xPos, yPos, width, height, &opts);
}

#endif

void draw_ellipse_opts(color clr, float xPos, float yPos, float width, float height, const drawing_options *opts)
{
    sg_Graphics_DrawEllipseOpts(clr, xPos, yPos, width, height, opts);
}

void draw_ellipse_opts_byval(color clr, float xPos, float yPos, float width, float height, const drawing_options opts)
{
    sg_Graphics_DrawEllipseOpts(clr, xPos, yPos, width, height, &opts);
}

#ifdef __cplusplus

void draw_line(color clr, const point2d &fromPt, const point2d &toPt)
{
    sg_Graphics_DrawLinePt2Pt(clr, &fromPt, &toPt);
}

#endif

void draw_line_pt2_pt(color clr, const point2d *fromPt, const point2d *toPt)
{
    sg_Graphics_DrawLinePt2Pt(clr, fromPt, toPt);
}

void draw_line_pt2_pt_byval(color clr, const point2d fromPt, const point2d toPt)
{
    sg_Graphics_DrawLinePt2Pt(clr, &fromPt, &toPt);
}

void draw_line(color clr, float x1, float y1, float x2, float y2)
{
    sg_Graphics_DrawLine(clr, x1, y1, x2, y2);
}

#ifdef __cplusplus

void draw_line(color clr, const line_segment &l)
{
    sg_Graphics_DrawLineStruct(clr, &l);
}

#endif

void draw_line_struct(color clr, const line_segment *l)
{
    sg_Graphics_DrawLineStruct(clr, l);
}

void draw_line_struct_byval(color clr, const line_segment l)
{
    sg_Graphics_DrawLineStruct(clr, &l);
}

#ifdef __cplusplus

void draw_line(color clr, const line_segment &l, const drawing_options &opts)
{
    sg_Graphics_DrawLineStructOpts(clr, &l, &opts);
}

#endif

void draw_line_struct_opts(color clr, const line_segment *l, const drawing_options *opts)
{
    sg_Graphics_DrawLineStructOpts(clr, l, opts);
}

void draw_line_struct_opts_byval(color clr, const line_segment l, const drawing_options opts)
{
    sg_Graphics_DrawLineStructOpts(clr, &l, &opts);
}

#ifdef __cplusplus

void draw_line(color clr, const point2d &fromPt, const point2d &toPt, const drawing_options &opts)
{
    sg_Graphics_DrawLinePt2PtOpts(clr, &fromPt, &toPt, &opts);
}

#endif

void draw_line_pt2_pt_opts(color clr, const point2d *fromPt, const point2d *toPt, const drawing_options *opts)
{
    sg_Graphics_DrawLinePt2PtOpts(clr, fromPt, toPt, opts);
}

void draw_line_pt2_pt_opts_byval(color clr, const point2d fromPt, const point2d toPt, const drawing_options opts)
{
    sg_Graphics_DrawLinePt2PtOpts(clr, &fromPt, &toPt, &opts);
}

#ifdef __cplusplus

void draw_line(color clr, float xPosStart, float yPosStart, float xPosEnd, float yPosEnd, const drawing_options &opts)
{
    sg_Graphics_DrawLineOpts(clr, xPosStart, yPosStart, xPosEnd, yPosEnd, &opts);
}

#endif

void draw_line_opts(color clr, float xPosStart, float yPosStart, float xPosEnd, float yPosEnd, const drawing_options *opts)
{
    sg_Graphics_DrawLineOpts(clr, xPosStart, yPosStart, xPosEnd, yPosEnd, opts);
}

void draw_line_opts_byval(color clr, float xPosStart, float yPosStart, float xPosEnd, float yPosEnd, const drawing_options opts)
{
    sg_Graphics_DrawLineOpts(clr, xPosStart, yPosStart, xPosEnd, yPosEnd, &opts);
}

#ifdef __cplusplus

void draw_pixel(color clr, const point2d &position)
{
    sg_Graphics_DrawPixelAtPoint(clr, &position);
}

#endif

void draw_pixel_at_point(color clr, const point2d *position)
{
    sg_Graphics_DrawPixelAtPoint(clr, position);
}

void draw_pixel_at_point_byval(color clr, const point2d position)
{
    sg_Graphics_DrawPixelAtPoint(clr, &position);
}

#ifdef __cplusplus

void draw_pixel(color clr, const point2d &position, const drawing_options &opts)
{
    sg_Graphics_DrawPixelAtPointOpts(clr, &position, &opts);
}

#endif

void draw_pixel_at_point_opts(color clr, const point2d *position, const drawing_options *opts)
{
    sg_Graphics_DrawPixelAtPointOpts(clr, position, opts);
}

void draw_pixel_at_point_opts_byval(color clr, const point2d position, const drawing_options opts)
{
    sg_Graphics_DrawPixelAtPointOpts(clr, &position, &opts);
}

void draw_pixel(color clr, float x, float y)
{
    sg_Graphics_DrawPixel(clr, x, y);
}

#ifdef __cplusplus

void draw_pixel(color clr, float x, float y, const drawing_options &opts)
{
    sg_Graphics_DrawPixelOpts(clr, x, y, &opts);
}

#endif

void draw_pixel_opts(color clr, float x, float y, const drawing_options *opts)
{
    sg_Graphics_DrawPixelOpts(clr, x, y, opts);
}

void draw_pixel_opts_byval(color clr, float x, float y, const drawing_options opts)
{
    sg_Graphics_DrawPixelOpts(clr, x, y, &opts);
}

#ifdef __cplusplus

void draw_quad(color clr, const quad &q)
{
    sg_Graphics_DrawQuadStruct(clr, &q);
}

#endif

void draw_quad_struct(color clr, const quad *q)
{
    sg_Graphics_DrawQuadStruct(clr, q);
}

void draw_quad_struct_byval(color clr, const quad q)
{
    sg_Graphics_DrawQuadStruct(clr, &q);
}

#ifdef __cplusplus

void draw_quad(color clr, const quad &q, const drawing_options &opts)
{
    sg_Graphics_DrawQuadStructOpts(clr, &q, &opts);
}

#endif

void draw_quad_struct_opts(color clr, const quad *q, const drawing_options *opts)
{
    sg_Graphics_DrawQuadStructOpts(clr, q, opts);
}

void draw_quad_struct_opts_byval(color clr, const quad q, const drawing_options opts)
{
    sg_Graphics_DrawQuadStructOpts(clr, &q, &opts);
}

void draw_rectangle(color clr, float x, float y, float width, float height)
{
    sg_Graphics_DrawRectangle(clr, x, y, width, height);
}

#ifdef __cplusplus

void draw_rectangle(color clr, const rectangle &rect)
{
    sg_Graphics_DrawRectangleStruct(clr, &rect);
}

#endif

void draw_rectangle_struct(color clr, const rectangle *rect)
{
    sg_Graphics_DrawRectangleStruct(clr, rect);
}

void draw_rectangle_struct_byval(color clr, const rectangle rect)
{
    sg_Graphics_DrawRectangleStruct(clr, &rect);
}

#ifdef __cplusplus

void draw_rectangle(color clr, const rectangle &rect, const drawing_options &opts)
{
    sg_Graphics_DrawRectangleStructOpts(clr, &rect, &opts);
}

#endif

void draw_rectangle_struct_opts(color clr, const rectangle *rect, const drawing_options *opts)
{
    sg_Graphics_DrawRectangleStructOpts(clr, rect, opts);
}

void draw_rectangle_struct_opts_byval(color clr, const rectangle rect, const drawing_options opts)
{
    sg_Graphics_DrawRectangleStructOpts(clr, &rect, &opts);
}

#ifdef __cplusplus

void draw_rectangle(color clr, float xPos, float yPos, float width, float height, const drawing_options &opts)
{
    sg_Graphics_DrawRectangleOpts(clr, xPos, yPos, width, height, &opts);
}

#endif

void draw_rectangle_opts(color clr, float xPos, float yPos, float width, float height, const drawing_options *opts)
{
    sg_Graphics_DrawRectangleOpts(clr, xPos, yPos, width, height, opts);
}

void draw_rectangle_opts_byval(color clr, float xPos, float yPos, float width, float height, const drawing_options opts)
{
    sg_Graphics_DrawRectangleOpts(clr, xPos, yPos, width, height, &opts);
}

void draw_triangle(color clr, float x1, float y1, float x2, float y2, float x3, float y3)
{
    sg_Graphics_DrawTriangle(clr, x1, y1, x2, y2, x3, y3);
}

#ifdef __cplusplus

void draw_triangle(color clr, const triangle  &tri)
{
    sg_Graphics_DrawTriangleStruct(clr, &tri);
}

#endif

void draw_triangle_struct(color clr, const triangle  *tri)
{
    sg_Graphics_DrawTriangleStruct(clr, tri);
}

void draw_triangle_struct_byval(color clr, const triangle  tri)
{
    sg_Graphics_DrawTriangleStruct(clr, &tri);
}

#ifdef __cplusplus

void draw_triangle(color clr, const triangle  &tri, const drawing_options &opts)
{
    sg_Graphics_DrawTriangleStructOpts(clr, &tri, &opts);
}

#endif

void draw_triangle_struct_opts(color clr, const triangle  *tri, const drawing_options *opts)
{
    sg_Graphics_DrawTriangleStructOpts(clr, tri, opts);
}

void draw_triangle_struct_opts_byval(color clr, const triangle  tri, const drawing_options opts)
{
    sg_Graphics_DrawTriangleStructOpts(clr, &tri, &opts);
}

#ifdef __cplusplus

void draw_triangle(color clr, float x1, float y1, float x2, float y2, float x3, float y3, const drawing_options &opts)
{
    sg_Graphics_DrawTriangleOpts(clr, x1, y1, x2, y2, x3, y3, &opts);
}

#endif

void draw_triangle_opts(color clr, float x1, float y1, float x2, float y2, float x3, float y3, const drawing_options *opts)
{
    sg_Graphics_DrawTriangleOpts(clr, x1, y1, x2, y2, x3, y3, opts);
}

void draw_triangle_opts_byval(color clr, float x1, float y1, float x2, float y2, float x3, float y3, const drawing_options opts)
{
    sg_Graphics_DrawTriangleOpts(clr, x1, y1, x2, y2, x3, y3, &opts);
}

void fill_circle(color clr, float x, float y, float radius)
{
    sg_Graphics_FillCircle(clr, x, y, radius);
}

#ifdef __cplusplus

void fill_circle(color clr, const circle &c)
{
    sg_Graphics_FillCircleStruct(clr, &c);
}

#endif

void fill_circle_struct(color clr, const circle *c)
{
    sg_Graphics_FillCircleStruct(clr, c);
}

void fill_circle_struct_byval(color clr, const circle c)
{
    sg_Graphics_FillCircleStruct(clr, &c);
}

#ifdef __cplusplus

void fill_circle(color clr, const circle &c, const drawing_options &opts)
{
    sg_Graphics_FillCircleStructOpts(clr, &c, &opts);
}

#endif

void fill_circle_struct_opts(color clr, const circle *c, const drawing_options *opts)
{
    sg_Graphics_FillCircleStructOpts(clr, c, opts);
}

void fill_circle_struct_opts_byval(color clr, const circle c, const drawing_options opts)
{
    sg_Graphics_FillCircleStructOpts(clr, &c, &opts);
}

#ifdef __cplusplus

void fill_circle(color clr, const point2d &pt, int32_t radius)
{
    sg_Graphics_FillCircleAtPoint(clr, &pt, radius);
}

#endif

void fill_circle_at_point(color clr, const point2d *pt, int32_t radius)
{
    sg_Graphics_FillCircleAtPoint(clr, pt, radius);
}

void fill_circle_at_point_byval(color clr, const point2d pt, int32_t radius)
{
    sg_Graphics_FillCircleAtPoint(clr, &pt, radius);
}

#ifdef __cplusplus

void fill_circle(color clr, const point2d &pt, int32_t radius, const drawing_options &opts)
{
    sg_Graphics_FillCircleAtPointWithOpts(clr, &pt, radius, &opts);
}

#endif

void fill_circle_at_point_with_opts(color clr, const point2d *pt, int32_t radius, const drawing_options *opts)
{
    sg_Graphics_FillCircleAtPointWithOpts(clr, pt, radius, opts);
}

void fill_circle_at_point_with_opts_byval(color clr, const point2d pt, int32_t radius, const drawing_options opts)
{
    sg_Graphics_FillCircleAtPointWithOpts(clr, &pt, radius, &opts);
}

#ifdef __cplusplus

void fill_circle(color clr, float x, float y, float radius, const drawing_options &opts)
{
    sg_Graphics_FillCircleOpts(clr, x, y, radius, &opts);
}

#endif

void fill_circle_opts(color clr, float x, float y, float radius, const drawing_options *opts)
{
    sg_Graphics_FillCircleOpts(clr, x, y, radius, opts);
}

void fill_circle_opts_byval(color clr, float x, float y, float radius, const drawing_options opts)
{
    sg_Graphics_FillCircleOpts(clr, x, y, radius, &opts);
}

void fill_ellipse(color clr, float xPos, float yPos, float width, float height)
{
    sg_Graphics_FillEllipse(clr, xPos, yPos, width, height);
}

#ifdef __cplusplus

void fill_ellipse(color clr, const rectangle &rec)
{
    sg_Graphics_FillEllipseStruct(clr, &rec);
}

#endif

void fill_ellipse_struct(color clr, const rectangle *rec)
{
    sg_Graphics_FillEllipseStruct(clr, rec);
}

void fill_ellipse_struct_byval(color clr, const rectangle rec)
{
    sg_Graphics_FillEllipseStruct(clr, &rec);
}

#ifdef __cplusplus

void fill_ellipse(color clr, const rectangle &rec, const drawing_options &opts)
{
    sg_Graphics_FillEllipseStructOpts(clr, &rec, &opts);
}

#endif

void fill_ellipse_struct_opts(color clr, const rectangle *rec, const drawing_options *opts)
{
    sg_Graphics_FillEllipseStructOpts(clr, rec, opts);
}

void fill_ellipse_struct_opts_byval(color clr, const rectangle rec, const drawing_options opts)
{
    sg_Graphics_FillEllipseStructOpts(clr, &rec, &opts);
}

#ifdef __cplusplus

void fill_ellipse(color clr, float xPos, float yPos, float width, float height, const drawing_options &opts)
{
    sg_Graphics_FillEllipseOpts(clr, xPos, yPos, width, height, &opts);
}

#endif

void fill_ellipse_opts(color clr, float xPos, float yPos, float width, float height, const drawing_options *opts)
{
    sg_Graphics_FillEllipseOpts(clr, xPos, yPos, width, height, opts);
}

void fill_ellipse_opts_byval(color clr, float xPos, float yPos, float width, float height, const drawing_options opts)
{
    sg_Graphics_FillEllipseOpts(clr, xPos, yPos, width, height, &opts);
}

#ifdef __cplusplus

void fill_quad(color clr, const quad &q)
{
    sg_Graphics_FillQuadStruct(clr, &q);
}

#endif

void fill_quad_struct(color clr, const quad *q)
{
    sg_Graphics_FillQuadStruct(clr, q);
}

void fill_quad_struct_byval(color clr, const quad q)
{
    sg_Graphics_FillQuadStruct(clr, &q);
}

#ifdef __cplusplus

void fill_quad(color clr, const quad &q, const drawing_options &opts)
{
    sg_Graphics_FillQuadStructOpts(clr, &q, &opts);
}

#endif

void fill_quad_struct_opts(color clr, const quad *q, const drawing_options *opts)
{
    sg_Graphics_FillQuadStructOpts(clr, q, opts);
}

void fill_quad_struct_opts_byval(color clr, const quad q, const drawing_options opts)
{
    sg_Graphics_FillQuadStructOpts(clr, &q, &opts);
}

void fill_rectangle(color clr, float x, float y, float width, float height)
{
    sg_Graphics_FillRectangle(clr, x, y, width, height);
}

#ifdef __cplusplus

void fill_rectangle(color clr, const rectangle &rect)
{
    sg_Graphics_FillRectangleStruct(clr, &rect);
}

#endif

void fill_rectangle_struct(color clr, const rectangle *rect)
{
    sg_Graphics_FillRectangleStruct(clr, rect);
}

void fill_rectangle_struct_byval(color clr, const rectangle rect)
{
    sg_Graphics_FillRectangleStruct(clr, &rect);
}

#ifdef __cplusplus

void fill_rectangle(color clr, const rectangle &rect, const drawing_options &opts)
{
    sg_Graphics_FillRectangleStructOpts(clr, &rect, &opts);
}

#endif

void fill_rectangle_struct_opts(color clr, const rectangle *rect, const drawing_options *opts)
{
    sg_Graphics_FillRectangleStructOpts(clr, rect, opts);
}

void fill_rectangle_struct_opts_byval(color clr, const rectangle rect, const drawing_options opts)
{
    sg_Graphics_FillRectangleStructOpts(clr, &rect, &opts);
}

#ifdef __cplusplus

void fill_rectangle(color clr, float xPos, float yPos, float width, float height, const drawing_options &opts)
{
    sg_Graphics_FillRectangleOpts(clr, xPos, yPos, width, height, &opts);
}

#endif

void fill_rectangle_opts(color clr, float xPos, float yPos, float width, float height, const drawing_options *opts)
{
    sg_Graphics_FillRectangleOpts(clr, xPos, yPos, width, height, opts);
}

void fill_rectangle_opts_byval(color clr, float xPos, float yPos, float width, float height, const drawing_options opts)
{
    sg_Graphics_FillRectangleOpts(clr, xPos, yPos, width, height, &opts);
}

void fill_triangle(color clr, float x1, float y1, float x2, float y2, float x3, float y3)
{
    sg_Graphics_FillTriangle(clr, x1, y1, x2, y2, x3, y3);
}

#ifdef __cplusplus

void fill_triangle(color clr, const triangle  &tri)
{
    sg_Graphics_FillTriangleStruct(clr, &tri);
}

#endif

void fill_triangle_struct(color clr, const triangle  *tri)
{
    sg_Graphics_FillTriangleStruct(clr, tri);
}

void fill_triangle_struct_byval(color clr, const triangle  tri)
{
    sg_Graphics_FillTriangleStruct(clr, &tri);
}

#ifdef __cplusplus

void fill_triangle(color clr, const triangle  &tri, const drawing_options &opts)
{
    sg_Graphics_FillTriangleStructOpts(clr, &tri, &opts);
}

#endif

void fill_triangle_struct_opts(color clr, const triangle  *tri, const drawing_options *opts)
{
    sg_Graphics_FillTriangleStructOpts(clr, tri, opts);
}

void fill_triangle_struct_opts_byval(color clr, const triangle  tri, const drawing_options opts)
{
    sg_Graphics_FillTriangleStructOpts(clr, &tri, &opts);
}

#ifdef __cplusplus

void fill_triangle(color clr, float x1, float y1, float x2, float y2, float x3, float y3, const drawing_options &opts)
{
    sg_Graphics_FillTriangleOpts(clr, x1, y1, x2, y2, x3, y3, &opts);
}

#endif

void fill_triangle_opts(color clr, float x1, float y1, float x2, float y2, float x3, float y3, const drawing_options *opts)
{
    sg_Graphics_FillTriangleOpts(clr, x1, y1, x2, y2, x3, y3, opts);
}

void fill_triangle_opts_byval(color clr, float x1, float y1, float x2, float y2, float x3, float y3, const drawing_options opts)
{
    sg_Graphics_FillTriangleOpts(clr, x1, y1, x2, y2, x3, y3, &opts);
}

#ifdef __cplusplus

color get_pixel(bitmap bmp, float x, float y)
{
    return sg_Graphics_GetPixelFromBitmap(bmp, x, y);
}

#endif

color get_pixel_from_bitmap(bitmap bmp, float x, float y)
{
    return sg_Graphics_GetPixelFromBitmap(bmp, x, y);
}

#ifdef __cplusplus

color get_pixel(window wnd, float x, float y)
{
    return sg_Graphics_GetPixelFromWindow(wnd, x, y);
}

#endif

color get_pixel_from_window(window wnd, float x, float y)
{
    return sg_Graphics_GetPixelFromWindow(wnd, x, y);
}

color get_pixel_from_screen(float x, float y)
{
    return sg_Graphics_GetPixelFromScreen(x, y);
}

unsigned char green_of(color c)
{
    return sg_Graphics_GreenOf(c);
}

color hsbcolor(float hue, float saturation, float brightness)
{
    return sg_Graphics_HSBColor(hue, saturation, brightness);
}

#ifdef __cplusplus

void hsbvalues_of(color c, float &h, float &s, float &b)
{
    sg_Graphics_HSBValuesOf(c, &h, &s, &b);
}

#endif

void hsbvalues_of(color c, float *h, float *s, float *b)
{
    sg_Graphics_HSBValuesOf(c, h, s, b);
}

float hue_of(color c)
{
    return sg_Graphics_HueOf(c);
}

int32_t number_of_resolutions()
{
    return sg_Graphics_NumberOfResolutions();
}

void open_graphics_window(const char *caption, int32_t width, int32_t height)
{
    sg_Graphics_OpenGraphicsWindow(caption, width, height);
}

#ifdef __cplusplus

void pop_clip()
{
    sg_Graphics_PopClipScreen();
}

#endif

void pop_clip_screen()
{
    sg_Graphics_PopClipScreen();
}

#ifdef __cplusplus

void pop_clip(bitmap bmp)
{
    sg_Graphics_PopClipForBitmap(bmp);
}

#endif

void pop_clip_for_bitmap(bitmap bmp)
{
    sg_Graphics_PopClipForBitmap(bmp);
}

#ifdef __cplusplus

void pop_clip(window wnd)
{
    sg_Graphics_PopClipForWindow(wnd);
}

#endif

void pop_clip_for_window(window wnd)
{
    sg_Graphics_PopClipForWindow(wnd);
}

#ifdef __cplusplus

void push_clip(const rectangle &r)
{
    sg_Graphics_PushClipRect(&r);
}

#endif

void push_clip_rect(const rectangle *r)
{
    sg_Graphics_PushClipRect(r);
}

void push_clip_rect_byval(const rectangle r)
{
    sg_Graphics_PushClipRect(&r);
}

#ifdef __cplusplus

void push_clip(bitmap bmp, const rectangle &r)
{
    sg_Graphics_PushClipRectForBitmap(bmp, &r);
}

#endif

void push_clip_rect_for_bitmap(bitmap bmp, const rectangle *r)
{
    sg_Graphics_PushClipRectForBitmap(bmp, r);
}

void push_clip_rect_for_bitmap_byval(bitmap bmp, const rectangle r)
{
    sg_Graphics_PushClipRectForBitmap(bmp, &r);
}

#ifdef __cplusplus

void push_clip(window wnd, const rectangle &r)
{
    sg_Graphics_PushClipRectForWindow(wnd, &r);
}

#endif

void push_clip_rect_for_window(window wnd, const rectangle *r)
{
    sg_Graphics_PushClipRectForWindow(wnd, r);
}

void push_clip_rect_for_window_byval(window wnd, const rectangle r)
{
    sg_Graphics_PushClipRectForWindow(wnd, &r);
}

color rgbacolor(unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha)
{
    return sg_Graphics_RGBAColor(red, green, blue, alpha);
}

color rgbafloat_color(float r, float g, float b, float a)
{
    return sg_Graphics_RGBAFloatColor(r, g, b, a);
}

color rgbcolor(unsigned char red, unsigned char green, unsigned char blue)
{
    return sg_Graphics_RGBAColor(red, green, blue, 255);
}

color rgbfloat_color(float r, float g, float b)
{
    return sg_Graphics_RGBFloatColor(r, g, b);
}

color random_color()
{
    return sg_Graphics_RandomColor();
}

color random_rgbcolor(unsigned char alpha)
{
    return sg_Graphics_RandomRGBColor(alpha);
}

unsigned char red_of(color c)
{
    return sg_Graphics_RedOf(c);
}

void refresh_screen()
{
    sg_Graphics_RefreshScreen();
}

#ifdef __cplusplus

void refresh_screen(int32_t TargetFPS)
{
    sg_Graphics_RefreshScreenRestrictFPS(TargetFPS);
}

#endif

void refresh_screen_restrict_fps(int32_t TargetFPS)
{
    sg_Graphics_RefreshScreenRestrictFPS(TargetFPS);
}

#ifdef __cplusplus

void refresh_screen(window wnd, int32_t targetFPS)
{
    sg_Graphics_RefreshScrenWindowFPS(wnd, targetFPS);
}

#endif

void refresh_scren_window_fps(window wnd, int32_t targetFPS)
{
    sg_Graphics_RefreshScrenWindowFPS(wnd, targetFPS);
}

void reset_clip()
{
    sg_Graphics_ResetClip();
}

#ifdef __cplusplus

void reset_clip(window wnd)
{
    sg_Graphics_ResetClipForWindow(wnd);
}

#endif

void reset_clip_for_window(window wnd)
{
    sg_Graphics_ResetClipForWindow(wnd);
}

#ifdef __cplusplus

void reset_clip(bitmap bmp)
{
    sg_Graphics_ResetClipForBitmap(bmp);
}

#endif

void reset_clip_for_bitmap(bitmap bmp)
{
    sg_Graphics_ResetClipForBitmap(bmp);
}

float saturation_of(color c)
{
    return sg_Graphics_SaturationOf(c);
}

#ifdef __cplusplus

void set_clip(const rectangle &r)
{
    sg_Graphics_SetClip(&r);
}

#endif

void set_clip(const rectangle *r)
{
    sg_Graphics_SetClip(r);
}

void set_clip_byval(const rectangle r)
{
    sg_Graphics_SetClip(&r);
}

#ifdef __cplusplus

void set_clip(bitmap bmp, const rectangle &r)
{
    sg_Graphics_SetClipForBitmap(bmp, &r);
}

#endif

void set_clip_for_bitmap(bitmap bmp, const rectangle *r)
{
    sg_Graphics_SetClipForBitmap(bmp, r);
}

void set_clip_for_bitmap_byval(bitmap bmp, const rectangle r)
{
    sg_Graphics_SetClipForBitmap(bmp, &r);
}

#ifdef __cplusplus

void set_clip(window wnd, const rectangle &r)
{
    sg_Graphics_SetClipForWindow(wnd, &r);
}

#endif

void set_clip_for_window(window wnd, const rectangle *r)
{
    sg_Graphics_SetClipForWindow(wnd, r);
}

void set_clip_for_window_byval(window wnd, const rectangle r)
{
    sg_Graphics_SetClipForWindow(wnd, &r);
}

void set_icon(const char *filename)
{
    sg_Graphics_SetIcon(filename);
}

void show_swin_game_splash_screen()
{
    sg_Graphics_ShowSwinGameSplashScreen();
}

void take_screenshot(const char *basename)
{
    sg_Graphics_TakeScreenshot(basename);
}

unsigned char transparency_of(color c)
{
    return sg_Graphics_TransparencyOf(c);
}

