/*
* Generated by SGWrapperGen - DO NOT EDIT!
*
* SwinGame wrapper for C - Timers
*
* Wrapping sgTimers.pas
*/

#include "SGSDK.h"
#include "Timers.h"

#include "Types.h"

timer create_timer()
{
    return sg_Timers_CreateTimer();
}

#ifdef __cplusplus

timer create_timer(const char *name)
{
    return sg_Timers_CreateTimerNamed(name);
}

#endif

timer create_timer_named(const char *name)
{
    return sg_Timers_CreateTimerNamed(name);
}

#ifdef __cplusplus

void free_timer(timer &toFree)
{
    sg_Timers_FreeTimer(&toFree);
}

#endif

void free_timer(timer *toFree)
{
    sg_Timers_FreeTimer(toFree);
}

#ifdef __cplusplus

void pause_timer(const char *name)
{
    sg_Timers_PauseTimerNamed(name);
}

#endif

void pause_timer_named(const char *name)
{
    sg_Timers_PauseTimerNamed(name);
}

void pause_timer(timer toPause)
{
    sg_Timers_PauseTimer(toPause);
}

void release_all_timers()
{
    sg_Timers_ReleaseAllTimers();
}

void release_timer(const char *name)
{
    sg_Timers_ReleaseTimer(name);
}

#ifdef __cplusplus

void reset_timer(const char *name)
{
    sg_Timers_ResetTimerNamed(name);
}

#endif

void reset_timer_named(const char *name)
{
    sg_Timers_ResetTimerNamed(name);
}

void reset_timer(timer tmr)
{
    sg_Timers_ResetTimer(tmr);
}

#ifdef __cplusplus

void resume_timer(const char *name)
{
    sg_Timers_ResumeTimerNamed(name);
}

#endif

void resume_timer_named(const char *name)
{
    sg_Timers_ResumeTimerNamed(name);
}

void resume_timer(timer toUnpause)
{
    sg_Timers_ResumeTimer(toUnpause);
}

void start_timer(timer toStart)
{
    sg_Timers_StartTimer(toStart);
}

#ifdef __cplusplus

void start_timer(const char *name)
{
    sg_Timers_StartTimerNamed(name);
}

#endif

void start_timer_named(const char *name)
{
    sg_Timers_StartTimerNamed(name);
}

void stop_timer(timer toStop)
{
    sg_Timers_StopTimer(toStop);
}

#ifdef __cplusplus

void stop_timer(const char *name)
{
    sg_Timers_StopTimerNamed(name);
}

#endif

void stop_timer_named(const char *name)
{
    sg_Timers_StopTimerNamed(name);
}

timer timer_named(const char *name)
{
    return sg_Timers_TimerNamed(name);
}

#ifdef __cplusplus

uint32_t timer_ticks(const char *name)
{
    return sg_Timers_TimerTicksNamed(name);
}

#endif

uint32_t timer_ticks_named(const char *name)
{
    return sg_Timers_TimerTicksNamed(name);
}

uint32_t timer_ticks(timer toGet)
{
    return sg_Timers_TimerTicks(toGet);
}

