/*
* Generated by SGWrapperGen - DO NOT EDIT!
*
* SwinGame wrapper for C - Utils
*
* Wrapping sgUtils.pas
*/

#ifndef sgUtils
#define sgUtils

#include <stdint.h>

#ifndef __cplusplus
  #include <stdbool.h>
#endif

#include "Types.h"

void calculate_framerate(char *average, char *highest, char *lowest, color *textColor);
void delay(uint32_t time);
void exception_message(char *result);
bool exception_occured();
int32_t get_framerate();
uint32_t get_ticks();
float rnd();
int32_t rnd_upto(int32_t ubound);
void swin_game_version(char *result);

#ifdef __cplusplus
// C++ overloaded functions
void calculate_framerate(char *average, char *highest, char *lowest, color &textColor);
int32_t rnd(int32_t ubound);

#endif

#endif

