/*
* Generated by SGWrapperGen - DO NOT EDIT!
*
* SwinGame wrapper for C - Web
*
* Wrapping sgWeb.pas
*/

#include "SGSDK.h"
#include "Web.h"

#include "Types.h"

#ifdef __cplusplus

void free_http_response(http_response &response)
{
    sg_Web_FreeHttpResponse(&response);
}

#endif

void free_http_response(http_response *response)
{
    sg_Web_FreeHttpResponse(response);
}

http_response http_get(const char *url, unsigned short int port)
{
    return sg_Web_HttpGet(url, port);
}

http_response http_post(const char *url, unsigned short int port, const char *body)
{
    return sg_Web_HttpPost(url, port, body);
}

void http_response_body_as_string(http_response httpData, char *result)
{
    sg_Web_HttpResponseBodyAsString(httpData, result);
}

