/*
* Generated by SGWrapperGen - DO NOT EDIT!
*
* SwinGame wrapper for C - Web
*
* Wrapping sgWeb.pas
*/

#ifndef sgWeb
#define sgWeb

#include <stdint.h>

#ifndef __cplusplus
  #include <stdbool.h>
#endif

#include "Types.h"

void free_http_response(http_response *response);
http_response http_get(const char *url, unsigned short int port);
http_response http_post(const char *url, unsigned short int port, const char *body);
void http_response_body_as_string(http_response httpData, char *result);

#ifdef __cplusplus
// C++ overloaded functions
void free_http_response(http_response &response);

#endif

#endif

