/*
* Generated by SGWrapperGen - DO NOT EDIT!
*
* SwinGame wrapper for C - WindowManager
*
* Wrapping sgWindowManager.pas
*/

#ifndef sgWindowManager
#define sgWindowManager

#include <stdint.h>

#ifndef __cplusplus
  #include <stdbool.h>
#endif

#include "Types.h"

void change_screen_size(int32_t width, int32_t height);
void change_window_size_named(const char *name, int32_t width, int32_t height);
void change_window_size(window wind, int32_t width, int32_t height);
void close_window(window wind);
void close_window_named(const char *name);
bool has_window(const char *name);
void move_window(window wind, int32_t x, int32_t y);
void move_window_named(const char *name, int32_t x, int32_t y);
window open_window(const char *caption, int32_t width, int32_t height);
void save_screenshot(window src, const char *filepath);
int32_t screen_height();
int32_t screen_width();
void set_current_window_named(const char *name);
void set_current_window(window wnd);
void toggle_full_screen();
void toggle_window_border();
window window_at_index(int32_t idx);
bool primary_window_close_requested();
bool window_close_requested(window wind);
int32_t window_count();
int32_t window_height(window wind);
int32_t window_height_named(const char *name);
window window_named(const char *name);
point2d window_position(window wind);
point2d window_position_named(const char *name);
int32_t window_width(window wind);
int32_t window_width_named(const char *name);
window window_with_focus();
int32_t window_x(window wind);
int32_t window_xnamed(const char *name);
int32_t window_ynamed(const char *name);
int32_t window_y(window wind);

#ifdef __cplusplus
// C++ overloaded functions
void change_window_size(const char *name, int32_t width, int32_t height);
void close_window(const char *name);
void move_window(const char *name, int32_t x, int32_t y);
void set_current_window(const char *name);
bool window_close_requested();
int32_t window_height(const char *name);
point2d window_position(const char *name);
int32_t window_width(const char *name);
int32_t window_x(const char *name);
int32_t window_y(const char *name);

#endif

#endif

